description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^0.1.3"
  path_drawing: "^0.4.1"
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Inter"
      fonts: 
        - 
          asset: "fonts/Inter-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Irish Grover"
      fonts: 
        - 
          asset: "fonts/IrishGrover-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Inder"
      fonts: 
        - 
          asset: "fonts/Inder-regular.ttf"
          style: "normal"
          weight: 400
  uses-material-design: true
