description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies:
  cupertino_icons: ^1.0.4
  # image_picker:
  cloud_firestore: ^3.1.17
  
  path_drawing: ^1.0.0
  flutter:
    sdk: "flutter"
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_storage: ^10.2.17
  url_launcher: ^6.1.3
  url_launcher_web: ^2.0.11
dev_dependencies:
  flutter_test:
    sdk: "flutter"
environment:
  sdk: ">=2.16.0 <3.0.0"
flutter:
  assets:
    - "assets/images/"
  fonts:
    - family: "Inter"
      fonts:
        - asset: "fonts/Inter-regular.ttf"
          style: "normal"
          weight: 400
    - family: "Irish Grover"
      fonts:
        - asset: "fonts/IrishGrover-regular.ttf"
          style: "normal"
          weight: 400
    - family: "Inder"
      fonts:
        - asset: "fonts/Inder-regular.ttf"
          style: "normal"
          weight: 400
  uses-material-design: true
