import 'package:flutter/material.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget7/generated/GeneratedStikeskrimcatkuaskecillemkayupitabekassilindertisuebamb.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget7/generated/GeneratedRectangle16Widget2.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget7/generated/GeneratedLogoutWidget3.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget7/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget7/generated/GeneratedVasBungaDariStikEsKrimWidget.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget7/generated/GeneratedHomeWidget3.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget7/generated/GeneratedImage1Widget2.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget7/generated/GeneratedTutorialWidget8.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget7/generated/GeneratedBahanWidget2.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget7/generated/GeneratedRectangle17Widget2.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget7/generated/Generatedsiapkandasarkerangkavascatstikeskrimtempelkanstikeskrim.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget7/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget7/generated/GeneratedEllipse1Widget2.dart';

/* Frame tutorial
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTutorialWidget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 39.0,
                top: 189.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 122.0,
                child: GeneratedRectangle16Widget2(),
              ),
              Positioned(
                left: 39.0,
                top: 363.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 146.0,
                child: GeneratedRectangle17Widget2(),
              ),
              Positioned(
                left: 127.0,
                top: 106.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 111.0,
                child: GeneratedEllipse1Widget2(),
              ),
              Positioned(
                left: 50.0,
                top: 229.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 105.0,
                child:
                    GeneratedStikeskrimcatkuaskecillemkayupitabekassilindertisuebamb(),
              ),
              Positioned(
                left: 50.0,
                top: 197.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 23.0,
                child: GeneratedBahanWidget2(),
              ),
              Positioned(
                left: -400.0,
                top: -2.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 89.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 36.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 47.0,
                child: GeneratedVasBungaDariStikEsKrimWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 28.0,
                child: GeneratedTutorialWidget8(),
              ),
              Positioned(
                left: 42.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 246.0,
                child:
                    Generatedsiapkandasarkerangkavascatstikeskrimtempelkanstikeskrim(),
              ),
              Positioned(
                left: 256.0,
                top: 81.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 68.0,
                child: GeneratedRectangle20Widget(),
              ),
              Positioned(
                left: 248.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 70.04717254638672,
                child: GeneratedImage1Widget2(),
              ),
              Positioned(
                left: 215.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 30.0,
                child: GeneratedHomeWidget3(),
              ),
              Positioned(
                left: 286.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 33.0,
                child: GeneratedLogoutWidget3(),
              )
            ]),
      ),
    ));
  }
}
