import 'package:flutter/material.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget3/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget3/generated/Generatedukurdanberigarispadastikeskrimpotongdenganrapitentukanp.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget3/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget3/generated/GeneratedStikeskrimGuntingLemfoxputihPenggarisPensilataubolpoint.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget3/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget3/generated/GeneratedTutorialWidget4.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget3/generated/GeneratedImage1Widget1.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget3/generated/GeneratedHomeWidget1.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget3/generated/GeneratedBahanWidget.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget3/generated/GeneratedLogoutWidget1.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget3/generated/GeneratedEllipse1Widget.dart';

/* Frame tutorial
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTutorialWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 36.0,
                top: 192.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 147.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 124.0,
                top: 117.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 111.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 234.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 105.0,
                child:
                    GeneratedStikeskrimGuntingLemfoxputihPenggarisPensilataubolpoint(),
              ),
              Positioned(
                left: 50.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 23.0,
                child: GeneratedBahanWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 28.0,
                child: GeneratedTutorialWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 23.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 94.0,
                child: GeneratedFrame1Widget(),
              ),
              Positioned(
                left: 248.0,
                top: 122.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 70.04717254638672,
                child: GeneratedImage1Widget1(),
              ),
              Positioned(
                left: 37.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 227.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 259.0,
                height: 207.0,
                child:
                    Generatedukurdanberigarispadastikeskrimpotongdenganrapitentukanp(),
              ),
              Positioned(
                left: 215.0,
                top: 4.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 30.0,
                child: GeneratedHomeWidget1(),
              ),
              Positioned(
                left: 286.0,
                top: 4.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 33.0,
                child: GeneratedLogoutWidget1(),
              )
            ]),
      ),
    ));
  }
}
