import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/mask/mask.dart';
import 'package:flutter/gestures.dart';
import 'package:url_launcher/url_launcher_string.dart';
import '../../main.dart';

/* Frame tutorial
    Autogenerated by FlutLab FTF Generator
  */
class TutorialPage7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: SingleChildScrollView(
          child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 1540.0,
          child: Stack(
              clipBehavior: Clip.none,
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 36.0,
                  top: 192.0,
                  right: null,
                  bottom: null,
                  width: 287.0,
                  height: 250.0,
                  child: Container(
                    width: 287.0,
                    height: 147.0,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(15.0),
                      border: Border.all(
                        width: 1.0,
                        color: Color.fromARGB(255, 0, 0, 0),
                      ),
                    ),
                    child: ClipRRect(
                      borderRadius: BorderRadius.circular(15.0),
                      child: Container(
                        color: Color.fromARGB(255, 255, 231, 252),
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 124.0,
                  top: 117.0,
                  right: null,
                  bottom: null,
                  width: 111.0,
                  height: 111.0,
                  child: Container(
                    width: 111.0,
                    height: 111.0,
                    child: Stack(
                        clipBehavior: Clip.none,
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: 0.0,
                            bottom: 0.0,
                            width: null,
                            height: null,
                            child: Mask.fromSVGPath(
                              'M111 55.5C111 86.1518 86.1518 111 55.5 111C24.8482 111 0 86.1518 0 55.5C0 24.8482 24.8482 0 55.5 0C86.1518 0 111 24.8482 111 55.5Z',
                              child: Image.asset(
                                "assets/images/magnet.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 111.0,
                                height: 111.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                              offset: Offset(0.0, 0.0),
                            ),
                          )
                        ]),
                  ),
                ),
                Positioned(
                  left: 50.0,
                  top: 234.0,
                  right: null,
                  bottom: null,
                  width: 261.0,
                  height: 105.0,
                  child: Text(
                    '''Cetakan resin, Zat pelepas cetakan, Lakban, Polyurethane casting resin, Katalis resin, Gelas ukur berskala, Pigmen warna, Pengering rambut atau senapan panas, Stik es krim dari kayu, Tusuk gigi kayu''',
                    overflow: TextOverflow.visible,
                    textAlign: TextAlign.left,
                    style: TextStyle(
                      height: 1.171875,
                      fontSize: 20.0,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      color: Color.fromARGB(255, 0, 0, 0),

                      /* letterSpacing: 0.0, */
                    ),
                  ),
                ),
                Positioned(
                  left: 50.0,
                  top: 202.0,
                  right: null,
                  bottom: null,
                  width: 85.0,
                  height: 23.0,
                  child: Text(
                    '''bahan :''',
                    overflow: TextOverflow.visible,
                    textAlign: TextAlign.left,
                    style: TextStyle(
                      height: 1.171875,
                      fontSize: 20.0,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      color: Color.fromARGB(255, 0, 0, 0),

                      /* letterSpacing: 0.0, */
                    ),
                  ),
                ),
                Positioned(
                  left: 43.0,
                  top: 450.0,
                  right: null,
                  bottom: null,
                  width: 91.0,
                  height: 28.0,
                  child: Text(
                    '''Tutorial :''',
                    overflow: TextOverflow.visible,
                    textAlign: TextAlign.left,
                    style: TextStyle(
                      height: 1.171875,
                      fontSize: 20.0,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      color: Color.fromARGB(255, 0, 0, 0),

                      /* letterSpacing: 0.0, */
                    ),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 23.0,
                  right: null,
                  bottom: null,
                  width: 360.0,
                  height: 94.0,
                  child: ClipRRect(
                    borderRadius: BorderRadius.zero,
                    child: Container(
                      width: 360.0,
                      height: 94.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            Positioned(
                              left: 22.0,
                              top: 17.0,
                              right: null,
                              bottom: null,
                              width: 315.0,
                              height: 47.0,
                              child: Text(
                                '''Hiasan Resin''',
                                overflow: TextOverflow.visible,
                                textAlign: TextAlign.center,
                                style: TextStyle(
                                  height: 1.171875,
                                  fontSize: 30.0,
                                  fontFamily: 'Irish Grover',
                                  fontWeight: FontWeight.w400,
                                  color: Color.fromARGB(255, 131, 111, 211),

                                  /* letterSpacing: 0.0, */
                                ),
                              ),
                            ),
                            Positioned(
                              left: 254.0,
                              top: 94.0,
                              right: null,
                              bottom: null,
                              width: 81.0,
                              height: 63.0,
                              child: Container(
                                width: 81.0,
                                height: 63.0,
                                child: ClipRRect(
                                  borderRadius: BorderRadius.zero,
                                  child: Container(
                                    color: Color.fromARGB(255, 196, 196, 196),
                                  ),
                                ),
                              ),
                            )
                          ]),
                    ),
                  ),
                ),
                Positioned(
                  left: 248.0,
                  top: 122.0,
                  right: null,
                  bottom: null,
                  width: 75.0,
                  height: 70.04717254638672,
                  child: Container(
                    width: 75.0,
                    height: 70.04717254638672,
                    child: ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Image.asset(
                        "assets/images/e8a2f2c65f62ce6e8fe19f550a8d96ecb63ef8e2.png",
                        color: null,
                        fit: BoxFit.cover,
                        width: 75.0,
                        height: 70.04717254638672,
                        colorBlendMode: BlendMode.dstATop,
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 37.0,
                  top: 500.0,
                  right: null,
                  bottom: null,
                  width: 287.0,
                  height: 400.0,
                  child: Container(
                    width: 287.0,
                    height: 600.0,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(15.0),
                      border: Border.all(
                        width: 1.0,
                        color: Color.fromARGB(255, 0, 0, 0),
                      ),
                    ),
                    child: ClipRRect(
                      borderRadius: BorderRadius.circular(15.0),
                      child: Container(
                        color: Color.fromARGB(255, 241, 191, 245),
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 50.0,
                  top: 500.0,
                  right: null,
                  bottom: null,
                  width: 259.0,
                  height: 207.0,
                  child: Text(
                    '''-Persiapkan hiasan dan persediaan.
-Siapkan Resin.
-Cetak Resin ke dalam cetakan resin.
-Buat perhiasan dari resin yang sudah mengeras.
-Hiasan Resin siap digunakan.''',
                    overflow: TextOverflow.visible,
                    textAlign: TextAlign.left,
                    style: TextStyle(
                      height: 1.171875,
                      fontSize: 20.0,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      color: Color.fromARGB(255, 0, 0, 0),

                      /* letterSpacing: 0.0, */
                    ),
                  ),
                ),
                Positioned(
                  left: 215.0,
                  top: 4.0,
                  right: null,
                  bottom: null,
                  width: 73.0,
                  height: 40.0,
                  child: Container(
                      margin: EdgeInsets.only(top: 20),
                      child: RichText(
                        text: TextSpan(
                            style: TextStyle(color: Colors.white, fontSize: 20),
                            children: [
                              TextSpan(
                                  recognizer: TapGestureRecognizer()
                                    ..onTap = () => Navigator.push(
                                        context,
                                        MaterialPageRoute(
                                            builder: (context) => MainPage())),
                                  text: 'Home |',
                                  style: TextStyle(
                                    decoration: TextDecoration.underline,
                                    color: Colors.black,
                                  ))
                            ]),
                      )),
                ),
                Positioned(
                  left: 50.0,
                  top: 950.0,
                  right: null,
                  bottom: null,
                  width: 259.0,
                  height: 100.0,
                  child: Container(
                    child: RichText(
                      text: new TextSpan(
                        children: [
                          new TextSpan(
                            text: 'Video Tutorial',
                            style: new TextStyle(color: Colors.blue),
                            recognizer: new TapGestureRecognizer()
                              ..onTap = () {
                                launchUrlString('https://youtu.be/2RM3Cw99cLA');
                              },
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ]),
        ),
      )),
    );
  }
}
