import 'package:flutter/material.dart';
// import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedRectangle11Widget.dart';
// import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedTutorialWidget1.dart';
// import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedRectangle8Widget.dart';
// import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedRectangle12Widget.dart';
// import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedRectangle7Widget.dart';
// import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedRectangle15Widget.dart';
// import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/DiyeyTitle.dart';
// import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedRectangle14Widget.dart';
// import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedRectangle9Widget.dart';
// import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/LogoutButton.dart';
// import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedRectangle7Widget1.dart';
// import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedRectangle13Widget.dart';
// import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedTutorialWidget2.dart';
// import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedTutorialWidget.dart';
// import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/diyeyapp/generatedtambahtutorialwidget1/GeneratedTambahtutorialWidget1.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget3/TutorialPage2.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget3/TutorialPage3.dart';
import '../generatedtutorialwidget3/TutorialPage1.dart';
import 'package:flutterapp/diyeyapp/generatedandroidsmall1widget/GeneratedAndroidSmall1Widget.dart';

import '../generatedtutorialwidget3/TutorialPage4.dart';
import '../generatedtutorialwidget3/TutorialPage5.dart';
import '../generatedtutorialwidget3/TutorialPage6.dart';
import '../generatedtutorialwidget3/TutorialPage7.dart';
import '../generatedtutorialwidget3/TutorialPage8.dart';
import '../generatedtutorialwidget3/TutorialPage9.dart';
import '../generatedtutorialwidget3/TutorialPage10.dart';
import '../generatedtutorialwidget3/TutorialPage11.dart';
import '../generatedtutorialwidget3/TutorialPage12.dart';
import '../generatedtutorialwidget3/TutorialPage13.dart';
import '../generatedtutorialwidget3/TutorialPage14.dart';
import '../generatedtutorialwidget3/TutorialPage15.dart';

/* Frame home
    Autogenerated by FlutLab FTF Generator
  */
class HomePage extends StatefulWidget {
  @override
  State<HomePage> createState() => _HomePage();
}

class _HomePage extends State<HomePage> {
  final user = FirebaseAuth.instance.currentUser!;

  @override
  Widget build(BuildContext context) {
    return Material(
        child: SingleChildScrollView(
            child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 460.0,
        height: 3000.0,
        // height: auto,
        child: Stack(
            clipBehavior: Clip.none,
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 231, 252),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 78.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 138.0,
                child: Container(
                  width: 178.0,
                  // height: MediaQuery.of(context).size.height,
                  height: 138.0,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(15.0),
                  ),
                  child: Container(
                    margin: EdgeInsets.only(top: 20),
                    width: 178.0,
                    child: ClipRRect(
                      borderRadius: BorderRadius.circular(15.0),
                      child: Image.asset(
                        "assets/images/cbb7e3d5ab7cb5093435f211bcecba59b078ac73.png",
                        color: null,
                        fit: BoxFit.cover,
                        width: 178.0,
                        height: 138.0,
                        colorBlendMode: BlendMode.dstATop,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 138.0,
                child: Container(
                  width: 178.0,
                  height: 138.0,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(15.0),
                  ),
                  child: ClipRRect(
                    borderRadius: BorderRadius.circular(15.0),
                    child: Image.asset(
                      "assets/images/6164d3ccf366369173ff51910bcef72043ae1af5.png",
                      color: null,
                      fit: BoxFit.cover,
                      width: 178.0,
                      height: 138.0,
                      colorBlendMode: BlendMode.dstATop,
                    ),
                  ),
                ),
              ),
              Positioned(
                  left: 24.0,
                  top: 408.0,
                  right: null,
                  bottom: null,
                  width: 178.0,
                  height: 2400.0,
                  child: Column(
                    children: [
                      Container(
                        // margin: EdgeInsets.only(top: 20),
                        width: 178.0,
                        height: 138.0,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(15.0),
                        ),
                        child: ClipRRect(
                          borderRadius: BorderRadius.circular(15.0),
                          child: Image.asset(
                            "assets/images/a5a7cafbe9140013a74748a9c65021b271c057e3.png",
                            color: null,
                            fit: BoxFit.cover,
                            width: 178.0,
                            height: 138.0,
                            colorBlendMode: BlendMode.dstATop,
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 30),
                        width: 178.0,
                        height: 138.0,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(15.0),
                        ),
                        child: ClipRRect(
                          borderRadius: BorderRadius.circular(15.0),
                          child: Image.asset(
                            "assets/images/Bom_Bath.jpg",
                            color: null,
                            fit: BoxFit.cover,
                            width: 178.0,
                            height: 138.0,
                            colorBlendMode: BlendMode.dstATop,
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 30),
                        width: 178.0,
                        height: 138.0,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(15.0),
                        ),
                        child: ClipRRect(
                          borderRadius: BorderRadius.circular(15.0),
                          child: Image.asset(
                            "assets/images/kuncir.jpg",
                            color: null,
                            fit: BoxFit.cover,
                            width: 178.0,
                            height: 138.0,
                            colorBlendMode: BlendMode.dstATop,
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 30),
                        width: 178.0,
                        height: 138.0,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(15.0),
                        ),
                        child: ClipRRect(
                          borderRadius: BorderRadius.circular(15.0),
                          child: Image.asset(
                            "assets/images/Lilin.png",
                            color: null,
                            fit: BoxFit.cover,
                            width: 178.0,
                            height: 138.0,
                            colorBlendMode: BlendMode.dstATop,
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 30),
                        width: 178.0,
                        height: 138.0,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(15.0),
                        ),
                        child: ClipRRect(
                          borderRadius: BorderRadius.circular(15.0),
                          child: Image.asset(
                            "assets/images/magnet.png",
                            color: null,
                            fit: BoxFit.cover,
                            width: 178.0,
                            height: 138.0,
                            colorBlendMode: BlendMode.dstATop,
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 30),
                        width: 178.0,
                        height: 138.0,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(15.0),
                        ),
                        child: ClipRRect(
                          borderRadius: BorderRadius.circular(15.0),
                          child: Image.asset(
                            "assets/images/milkbath.png",
                            color: null,
                            fit: BoxFit.cover,
                            width: 178.0,
                            height: 138.0,
                            colorBlendMode: BlendMode.dstATop,
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 30),
                        width: 178.0,
                        height: 138.0,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(15.0),
                        ),
                        child: ClipRRect(
                          borderRadius: BorderRadius.circular(15.0),
                          child: Image.asset(
                            "assets/images/notecard.jpg",
                            color: null,
                            fit: BoxFit.cover,
                            width: 178.0,
                            height: 138.0,
                            colorBlendMode: BlendMode.dstATop,
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 30),
                        width: 178.0,
                        height: 138.0,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(15.0),
                        ),
                        child: ClipRRect(
                          borderRadius: BorderRadius.circular(15.0),
                          child: Image.asset(
                            "assets/images/Pet.png",
                            color: null,
                            fit: BoxFit.cover,
                            width: 178.0,
                            height: 138.0,
                            colorBlendMode: BlendMode.dstATop,
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 30),
                        width: 178.0,
                        height: 138.0,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(15.0),
                        ),
                        child: ClipRRect(
                          borderRadius: BorderRadius.circular(15.0),
                          child: Image.asset(
                            "assets/images/rambut_gimbal.jpg",
                            color: null,
                            fit: BoxFit.cover,
                            width: 178.0,
                            height: 138.0,
                            colorBlendMode: BlendMode.dstATop,
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 30),
                        width: 178.0,
                        height: 138.0,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(15.0),
                        ),
                        child: ClipRRect(
                          borderRadius: BorderRadius.circular(15.0),
                          child: Image.asset(
                            "assets/images/soap.jpg",
                            color: null,
                            fit: BoxFit.cover,
                            width: 178.0,
                            height: 138.0,
                            colorBlendMode: BlendMode.dstATop,
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 30),
                        width: 178.0,
                        height: 138.0,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(15.0),
                        ),
                        child: ClipRRect(
                          borderRadius: BorderRadius.circular(15.0),
                          child: Image.asset(
                            "assets/images/wallart.png",
                            color: null,
                            fit: BoxFit.cover,
                            width: 178.0,
                            height: 138.0,
                            colorBlendMode: BlendMode.dstATop,
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 30),
                        width: 178.0,
                        height: 138.0,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(15.0),
                        ),
                        child: ClipRRect(
                          borderRadius: BorderRadius.circular(15.0),
                          child: Image.asset(
                            "assets/images/jepit.jpg",
                            color: null,
                            fit: BoxFit.cover,
                            width: 178.0,
                            height: 138.0,
                            colorBlendMode: BlendMode.dstATop,
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 30),
                        width: 178.0,
                        height: 138.0,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(15.0),
                        ),
                        child: ClipRRect(
                          borderRadius: BorderRadius.circular(15.0),
                          child: Image.asset(
                            "assets/images/tempatsampah.jpg",
                            color: null,
                            fit: BoxFit.cover,
                            width: 178.0,
                            height: 138.0,
                            colorBlendMode: BlendMode.dstATop,
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 20),
                        child: ElevatedButton(
                          child: Text(
                            '''Tambah Tutorial''',
                          ),
                          style: ElevatedButton.styleFrom(
                              primary: Color.fromARGB(255, 167, 146, 250),
                              shape: new RoundedRectangleBorder(
                                borderRadius: new BorderRadius.circular(30.0),
                              ),
                              minimumSize: Size(100, 36)),
                          onPressed: () => Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) => TambahTutorPage())),
                        ),
                      ),
                    ],
                  )),
              // Positioned(
              //   left: 24.0,
              //   top: 580.0,
              //   right: null,
              //   bottom: null,
              //   width: 178.0,
              //   height: 138.0,
              //   child: Container(
              //     width: 178.0,
              //     height: 138.0,
              //     decoration: BoxDecoration(
              //       borderRadius: BorderRadius.circular(15.0),
              //     ),
              //     child: ClipRRect(
              //       borderRadius: BorderRadius.circular(15.0),
              //       child: Image.asset(
              //         "assets/images/a5a7cafbe9140013a74748a9c65021b271c057e3.png",
              //         color: null,
              //         fit: BoxFit.cover,
              //         width: 178.0,
              //         height: 138.0,
              //         colorBlendMode: BlendMode.dstATop,
              //       ),
              //     ),
              //   ),
              // ),
              Positioned(
                left: 126.0,
                top: 28.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 55.0,
                child: Text(
                  '''DIYey''',
                  overflow: TextOverflow.visible,
                  textAlign: TextAlign.left,
                  style: TextStyle(
                    height: 1.171875,
                    fontSize: 40.0,
                    fontFamily: 'Irish Grover',
                    fontWeight: FontWeight.w400,
                    color: Color.fromARGB(255, 131, 111, 211),

                    /* letterSpacing: 0.0, */
                  ),
                ),
              ),
              Positioned(
                left: 180.0,
                top: 186.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GestureDetector(
                  onTap: () => Navigator.push(
                      context,
                      MaterialPageRoute(
                          builder: (context) =>
                              GeneratedAndroidSmall1Widget())),
                  child: Container(
                    width: 40.0,
                    height: 40.0,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(180.0),
                    ),
                    child: ClipRRect(
                      borderRadius: BorderRadius.circular(180.0),
                      child: Image.asset(
                        "assets/images/e31fed0fed011fa2146e60aeff6efa2f04a59d14.png",
                        color: null,
                        fit: BoxFit.cover,
                        width: 40.0,
                        height: 40.0,
                        colorBlendMode: BlendMode.dstATop,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 180.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GestureDetector(
                  onTap: () => Navigator.push(
                      context,
                      MaterialPageRoute(
                          builder: (context) =>
                              GeneratedAndroidSmall1Widget())),
                  child: Container(
                    width: 40.0,
                    height: 40.0,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(180.0),
                    ),
                    child: ClipRRect(
                      borderRadius: BorderRadius.circular(180.0),
                      child: Image.asset(
                        "assets/images/e31fed0fed011fa2146e60aeff6efa2f04a59d14.png",
                        color: null,
                        fit: BoxFit.cover,
                        width: 40.0,
                        height: 40.0,
                        colorBlendMode: BlendMode.dstATop,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                  left: 182.0,
                  top: 516.0,
                  right: null,
                  bottom: null,
                  width: 40.0,
                  height: 2400.0,
                  child: Column(
                    children: [
                      Container(
                        child: GestureDetector(
                          onTap: () => Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) =>
                                      GeneratedAndroidSmall1Widget())),
                          child: Container(
                            width: 40.0,
                            height: 40.0,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(180.0),
                            ),
                            child: ClipRRect(
                              borderRadius: BorderRadius.circular(180.0),
                              child: Image.asset(
                                "assets/images/e31fed0fed011fa2146e60aeff6efa2f04a59d14.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 40.0,
                                height: 40.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 138),
                        child: GestureDetector(
                          onTap: () => Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) =>
                                      GeneratedAndroidSmall1Widget())),
                          child: Container(
                            width: 40.0,
                            height: 40.0,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(180.0),
                            ),
                            child: ClipRRect(
                              borderRadius: BorderRadius.circular(180.0),
                              child: Image.asset(
                                "assets/images/e31fed0fed011fa2146e60aeff6efa2f04a59d14.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 40.0,
                                height: 40.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 134),
                        child: GestureDetector(
                          onTap: () => Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) =>
                                      GeneratedAndroidSmall1Widget())),
                          child: Container(
                            width: 40.0,
                            height: 40.0,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(180.0),
                            ),
                            child: ClipRRect(
                              borderRadius: BorderRadius.circular(180.0),
                              child: Image.asset(
                                "assets/images/e31fed0fed011fa2146e60aeff6efa2f04a59d14.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 40.0,
                                height: 40.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 130),
                        child: GestureDetector(
                          onTap: () => Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) =>
                                      GeneratedAndroidSmall1Widget())),
                          child: Container(
                            width: 40.0,
                            height: 40.0,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(180.0),
                            ),
                            child: ClipRRect(
                              borderRadius: BorderRadius.circular(180.0),
                              child: Image.asset(
                                "assets/images/e31fed0fed011fa2146e60aeff6efa2f04a59d14.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 40.0,
                                height: 40.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 128),
                        child: GestureDetector(
                          onTap: () => Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) =>
                                      GeneratedAndroidSmall1Widget())),
                          child: Container(
                            width: 40.0,
                            height: 40.0,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(180.0),
                            ),
                            child: ClipRRect(
                              borderRadius: BorderRadius.circular(180.0),
                              child: Image.asset(
                                "assets/images/e31fed0fed011fa2146e60aeff6efa2f04a59d14.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 40.0,
                                height: 40.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 128),
                        child: GestureDetector(
                          onTap: () => Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) =>
                                      GeneratedAndroidSmall1Widget())),
                          child: Container(
                            width: 40.0,
                            height: 40.0,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(180.0),
                            ),
                            child: ClipRRect(
                              borderRadius: BorderRadius.circular(180.0),
                              child: Image.asset(
                                "assets/images/e31fed0fed011fa2146e60aeff6efa2f04a59d14.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 40.0,
                                height: 40.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 128),
                        child: GestureDetector(
                          onTap: () => Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) =>
                                      GeneratedAndroidSmall1Widget())),
                          child: Container(
                            width: 40.0,
                            height: 40.0,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(180.0),
                            ),
                            child: ClipRRect(
                              borderRadius: BorderRadius.circular(180.0),
                              child: Image.asset(
                                "assets/images/e31fed0fed011fa2146e60aeff6efa2f04a59d14.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 40.0,
                                height: 40.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 128),
                        child: GestureDetector(
                          onTap: () => Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) =>
                                      GeneratedAndroidSmall1Widget())),
                          child: Container(
                            width: 40.0,
                            height: 40.0,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(180.0),
                            ),
                            child: ClipRRect(
                              borderRadius: BorderRadius.circular(180.0),
                              child: Image.asset(
                                "assets/images/e31fed0fed011fa2146e60aeff6efa2f04a59d14.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 40.0,
                                height: 40.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 128),
                        child: GestureDetector(
                          onTap: () => Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) =>
                                      GeneratedAndroidSmall1Widget())),
                          child: Container(
                            width: 40.0,
                            height: 40.0,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(180.0),
                            ),
                            child: ClipRRect(
                              borderRadius: BorderRadius.circular(180.0),
                              child: Image.asset(
                                "assets/images/e31fed0fed011fa2146e60aeff6efa2f04a59d14.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 40.0,
                                height: 40.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 128),
                        child: GestureDetector(
                          onTap: () => Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) =>
                                      GeneratedAndroidSmall1Widget())),
                          child: Container(
                            width: 40.0,
                            height: 40.0,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(180.0),
                            ),
                            child: ClipRRect(
                              borderRadius: BorderRadius.circular(180.0),
                              child: Image.asset(
                                "assets/images/e31fed0fed011fa2146e60aeff6efa2f04a59d14.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 40.0,
                                height: 40.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 128),
                        child: GestureDetector(
                          onTap: () => Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) =>
                                      GeneratedAndroidSmall1Widget())),
                          child: Container(
                            width: 40.0,
                            height: 40.0,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(180.0),
                            ),
                            child: ClipRRect(
                              borderRadius: BorderRadius.circular(180.0),
                              child: Image.asset(
                                "assets/images/e31fed0fed011fa2146e60aeff6efa2f04a59d14.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 40.0,
                                height: 40.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 128),
                        child: GestureDetector(
                          onTap: () => Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) =>
                                      GeneratedAndroidSmall1Widget())),
                          child: Container(
                            width: 40.0,
                            height: 40.0,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(180.0),
                            ),
                            child: ClipRRect(
                              borderRadius: BorderRadius.circular(180.0),
                              child: Image.asset(
                                "assets/images/e31fed0fed011fa2146e60aeff6efa2f04a59d14.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 40.0,
                                height: 40.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.only(top: 128),
                        child: GestureDetector(
                          onTap: () => Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) =>
                                      GeneratedAndroidSmall1Widget())),
                          child: Container(
                            width: 40.0,
                            height: 40.0,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(180.0),
                            ),
                            child: ClipRRect(
                              borderRadius: BorderRadius.circular(180.0),
                              child: Image.asset(
                                "assets/images/e31fed0fed011fa2146e60aeff6efa2f04a59d14.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 40.0,
                                height: 40.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                          ),
                        ),
                      )
                    ],
                  )),
              Positioned(
                left: 180.0,
                top: 84.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 41.0,
                child: Container(
                  margin: EdgeInsets.only(top: 20),
                  child: ElevatedButton(
                    child: Text(
                      '''Tutorial''',
                    ),
                    style: ElevatedButton.styleFrom(
                        primary: Color.fromARGB(255, 167, 146, 250),
                        shape: new RoundedRectangleBorder(
                          borderRadius: new BorderRadius.circular(30.0),
                        ),
                        minimumSize: Size(100, 36)),
                    onPressed: () => Navigator.push(
                        context,
                        MaterialPageRoute(
                            builder: (context) => TutorialPage1())),
                  ),
                ),
              ),
              Positioned(
                left: 180.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 41.0,
                child: Container(
                  margin: EdgeInsets.only(top: 20),
                  child: ElevatedButton(
                    child: Text(
                      '''Tutorial''',
                    ),
                    style: ElevatedButton.styleFrom(
                        primary: Color.fromARGB(255, 167, 146, 250),
                        shape: new RoundedRectangleBorder(
                          borderRadius: new BorderRadius.circular(30.0),
                        ),
                        minimumSize: Size(100, 36)),
                    onPressed: () => Navigator.push(
                        context,
                        MaterialPageRoute(
                            builder: (context) => TutorialPage2())),
                  ),
                ),
              ),
              Positioned(
                left: 180.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 2200.0,
                child: Column(
                  children: [
                    Container(
                      margin: EdgeInsets.only(top: 20),
                      child: ElevatedButton(
                        child: Text(
                          '''Tutorial''',
                        ),
                        style: ElevatedButton.styleFrom(
                            primary: Color.fromARGB(255, 167, 146, 250),
                            shape: new RoundedRectangleBorder(
                              borderRadius: new BorderRadius.circular(30.0),
                            ),
                            minimumSize: Size(130, 36)),
                        onPressed: () => Navigator.push(
                            context,
                            MaterialPageRoute(
                                builder: (context) => TutorialPage3())),
                      ),
                    ),
                    Container(
                      margin: EdgeInsets.only(top: 140),
                      child: ElevatedButton(
                        child: Text(
                          '''Tutorial''',
                        ),
                        style: ElevatedButton.styleFrom(
                            primary: Color.fromARGB(255, 167, 146, 250),
                            shape: new RoundedRectangleBorder(
                              borderRadius: new BorderRadius.circular(30.0),
                            ),
                            minimumSize: Size(130, 36)),
                        onPressed: () => Navigator.push(
                            context,
                            MaterialPageRoute(
                                builder: (context) => TutorialPage4())),
                      ),
                    ),
                    Container(
                      margin: EdgeInsets.only(top: 130),
                      child: ElevatedButton(
                        child: Text(
                          '''Tutorial''',
                        ),
                        style: ElevatedButton.styleFrom(
                            primary: Color.fromARGB(255, 167, 146, 250),
                            shape: new RoundedRectangleBorder(
                              borderRadius: new BorderRadius.circular(30.0),
                            ),
                            minimumSize: Size(130, 36)),
                        onPressed: () => Navigator.push(
                            context,
                            MaterialPageRoute(
                                builder: (context) => TutorialPage5())),
                      ),
                    ),
                    Container(
                      margin: EdgeInsets.only(top: 138),
                      child: ElevatedButton(
                        child: Text(
                          '''Tutorial''',
                        ),
                        style: ElevatedButton.styleFrom(
                            primary: Color.fromARGB(255, 167, 146, 250),
                            shape: new RoundedRectangleBorder(
                              borderRadius: new BorderRadius.circular(30.0),
                            ),
                            minimumSize: Size(130, 36)),
                        onPressed: () => Navigator.push(
                            context,
                            MaterialPageRoute(
                                builder: (context) => TutorialPage6())),
                      ),
                    ),
                    Container(
                      margin: EdgeInsets.only(top: 140),
                      child: ElevatedButton(
                        child: Text(
                          '''Tutorial''',
                        ),
                        style: ElevatedButton.styleFrom(
                            primary: Color.fromARGB(255, 167, 146, 250),
                            shape: new RoundedRectangleBorder(
                              borderRadius: new BorderRadius.circular(30.0),
                            ),
                            minimumSize: Size(130, 36)),
                        onPressed: () => Navigator.push(
                            context,
                            MaterialPageRoute(
                                builder: (context) => TutorialPage7())),
                      ),
                    ),
                    Container(
                      margin: EdgeInsets.only(top: 140),
                      child: ElevatedButton(
                        child: Text(
                          '''Tutorial''',
                        ),
                        style: ElevatedButton.styleFrom(
                            primary: Color.fromARGB(255, 167, 146, 250),
                            shape: new RoundedRectangleBorder(
                              borderRadius: new BorderRadius.circular(30.0),
                            ),
                            minimumSize: Size(130, 36)),
                        onPressed: () => Navigator.push(
                            context,
                            MaterialPageRoute(
                                builder: (context) => TutorialPage8())),
                      ),
                    ),
                    Container(
                      margin: EdgeInsets.only(top: 140),
                      child: ElevatedButton(
                        child: Text(
                          '''Tutorial''',
                        ),
                        style: ElevatedButton.styleFrom(
                            primary: Color.fromARGB(255, 167, 146, 250),
                            shape: new RoundedRectangleBorder(
                              borderRadius: new BorderRadius.circular(30.0),
                            ),
                            minimumSize: Size(130, 36)),
                        onPressed: () => Navigator.push(
                            context,
                            MaterialPageRoute(
                                builder: (context) => TutorialPage9())),
                      ),
                    ),
                    Container(
                      margin: EdgeInsets.only(top: 140),
                      child: ElevatedButton(
                        child: Text(
                          '''Tutorial''',
                        ),
                        style: ElevatedButton.styleFrom(
                            primary: Color.fromARGB(255, 167, 146, 250),
                            shape: new RoundedRectangleBorder(
                              borderRadius: new BorderRadius.circular(30.0),
                            ),
                            minimumSize: Size(130, 36)),
                        onPressed: () => Navigator.push(
                            context,
                            MaterialPageRoute(
                                builder: (context) => TutorialPage10())),
                      ),
                    ),
                    Container(
                      margin: EdgeInsets.only(top: 140),
                      child: ElevatedButton(
                        child: Text(
                          '''Tutorial''',
                        ),
                        style: ElevatedButton.styleFrom(
                            primary: Color.fromARGB(255, 167, 146, 250),
                            shape: new RoundedRectangleBorder(
                              borderRadius: new BorderRadius.circular(30.0),
                            ),
                            minimumSize: Size(130, 36)),
                        onPressed: () => Navigator.push(
                            context,
                            MaterialPageRoute(
                                builder: (context) => TutorialPage11())),
                      ),
                    ),
                    Container(
                      margin: EdgeInsets.only(top: 140),
                      child: ElevatedButton(
                        child: Text(
                          '''Tutorial''',
                        ),
                        style: ElevatedButton.styleFrom(
                            primary: Color.fromARGB(255, 167, 146, 250),
                            shape: new RoundedRectangleBorder(
                              borderRadius: new BorderRadius.circular(30.0),
                            ),
                            minimumSize: Size(130, 36)),
                        onPressed: () => Navigator.push(
                            context,
                            MaterialPageRoute(
                                builder: (context) => TutorialPage12())),
                      ),
                    ),
                    Container(
                      margin: EdgeInsets.only(top: 140),
                      child: ElevatedButton(
                        child: Text(
                          '''Tutorial''',
                        ),
                        style: ElevatedButton.styleFrom(
                            primary: Color.fromARGB(255, 167, 146, 250),
                            shape: new RoundedRectangleBorder(
                              borderRadius: new BorderRadius.circular(30.0),
                            ),
                            minimumSize: Size(130, 36)),
                        onPressed: () => Navigator.push(
                            context,
                            MaterialPageRoute(
                                builder: (context) => TutorialPage13())),
                      ),
                    ),
                    Container(
                      margin: EdgeInsets.only(top: 140),
                      child: ElevatedButton(
                        child: Text(
                          '''Tutorial''',
                        ),
                        style: ElevatedButton.styleFrom(
                            primary: Color.fromARGB(255, 167, 146, 250),
                            shape: new RoundedRectangleBorder(
                              borderRadius: new BorderRadius.circular(30.0),
                            ),
                            minimumSize: Size(130, 36)),
                        onPressed: () => Navigator.push(
                            context,
                            MaterialPageRoute(
                                builder: (context) => TutorialPage14())),
                      ),
                    ),
                    Container(
                      margin: EdgeInsets.only(top: 140),
                      child: ElevatedButton(
                        child: Text(
                          '''Tutorial''',
                        ),
                        style: ElevatedButton.styleFrom(
                            primary: Color.fromARGB(255, 167, 146, 250),
                            shape: new RoundedRectangleBorder(
                              borderRadius: new BorderRadius.circular(30.0),
                            ),
                            minimumSize: Size(130, 36)),
                        onPressed: () => Navigator.push(
                            context,
                            MaterialPageRoute(
                                builder: (context) => TutorialPage15())),
                      ),
                    ),
                  ],
                ),
              ),
              // Positioned(
              //   left: 206.0,
              //   top: 87.0,
              //   right: null,
              //   bottom: null,
              //   width: 89.0,
              //   height: 33.0,
              //   child: GeneratedTutorialWidget(),
              // ),
              // Positioned(
              //   left: 202.0,
              //   top: 250.0,
              //   right: null,
              //   bottom: null,
              //   width: 90.0,
              //   height: 33.0,
              //   child: GeneratedTutorialWidget1(),
              // ),
              // Positioned(
              //   left: 200.0,
              //   top: 418.0,
              //   right: null,
              //   bottom: null,
              //   width: 90.0,
              //   height: 32.0,
              //   child: GeneratedTutorialWidget2(),
              // ),
              // Positioned(
              //   left: 78.0,
              //   top: 740.0,
              //   right: null,
              //   bottom: null,
              //   width: 203.0,
              //   height: 41.0,
              //   child:
              // ),
              // // Positioned(
              //   left: 91.0,
              //   top: 581.0,
              //   right: null,
              //   bottom: null,
              //   width: 183.0,
              //   height: 26.0,
              //   child: GeneratedTambahtutorialWidget(),
              // ),
              Positioned(
                left: 252.0,
                top: 9.0,
                right: null,
                bottom: null,
                width: 168.0,
                height: 24.0,
                child: SizedBox(
                  height: 30,
                  width: 100,
                  child: ElevatedButton(
                    style: ElevatedButton.styleFrom(
                      primary: Color.fromARGB(255, 255, 255, 255),
                      shape: new RoundedRectangleBorder(
                        borderRadius: new BorderRadius.circular(30.0),
                      ),
                    ),
                    onPressed: () => FirebaseAuth.instance.signOut(),
                    child: const Text(
                      '''Logout''',
                      style: TextStyle(
                        fontFamily: 'Inter',
                        color: Color.fromARGB(255, 0, 0, 0),
                      ),
                    ),
                  ),
                ),
              )
            ]),
      ),
    )));
  }
}
