import 'package:flutter/material.dart';
import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedTutorialWidget1.dart';
import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedDIYeyWidget.dart';
import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedLogoutWidget.dart';
import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedRectangle7Widget1.dart';
import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedTutorialWidget2.dart';
import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedTutorialWidget.dart';
import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/diyeyapp/generatedhomewidget/generated/GeneratedTambahtutorialWidget.dart';

/* Frame home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 231, 252),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 78.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 138.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 138.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 408.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 138.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 126.0,
                top: 28.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 55.0,
                child: GeneratedDIYeyWidget(),
              ),
              Positioned(
                left: 180.0,
                top: 186.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 180.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedRectangle11Widget(),
              ),
              Positioned(
                left: 182.0,
                top: 526.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 180.0,
                top: 84.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 31.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 180.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 31.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 180.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 31.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 206.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 33.0,
                child: GeneratedTutorialWidget(),
              ),
              Positioned(
                left: 202.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 33.0,
                child: GeneratedTutorialWidget1(),
              ),
              Positioned(
                left: 200.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 32.0,
                child: GeneratedTutorialWidget2(),
              ),
              Positioned(
                left: 78.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 41.0,
                child: GeneratedRectangle7Widget1(),
              ),
              Positioned(
                left: 91.0,
                top: 581.0,
                right: null,
                bottom: null,
                width: 183.0,
                height: 26.0,
                child: GeneratedTambahtutorialWidget(),
              ),
              Positioned(
                left: 272.0,
                top: 9.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 33.0,
                child: GeneratedLogoutWidget(),
              )
            ]),
      ),
    ));
  }
}
