import 'package:flutter/material.dart';
import 'package:flutterapp/diyeyapp/generatedandroidsmall1widget/generated/GeneratedHomeWidget5.dart';
import 'package:flutterapp/diyeyapp/generatedandroidsmall1widget/generated/GeneratedLogoutWidget5.dart';
import 'package:flutterapp/diyeyapp/generatedandroidsmall1widget/generated/GeneratedRectangle28Widget.dart';
import 'package:flutterapp/diyeyapp/generatedandroidsmall1widget/generated/GeneratedRectangle16Widget3.dart';
import 'package:flutterapp/diyeyapp/generatedandroidsmall1widget/generated/GeneratedRectangle29Widget.dart';
import 'package:flutterapp/diyeyapp/generatedandroidsmall1widget/generated/GeneratedImage2Widget1.dart';
import 'package:flutterapp/diyeyapp/generatedandroidsmall1widget/generated/GeneratedFavoritWidget.dart';
import 'package:flutterapp/diyeyapp/generatedandroidsmall1widget/generated/GeneratedRectangle27Widget.dart';

/* Frame Android Small - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 34.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 283.0,
                child: GeneratedImage2Widget1(),
              ),
              Positioned(
                left: 56.0,
                top: 57.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 65.0,
                child: GeneratedFavoritWidget(),
              ),
              Positioned(
                left: 26.0,
                top: 119.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 131.0,
                child: GeneratedRectangle27Widget(),
              ),
              Positioned(
                left: 26.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 131.0,
                child: GeneratedRectangle28Widget(),
              ),
              Positioned(
                left: 183.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: GeneratedRectangle16Widget3(),
              ),
              Positioned(
                left: 180.0,
                top: 416.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: GeneratedRectangle29Widget(),
              ),
              Positioned(
                left: 215.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 30.0,
                child: GeneratedHomeWidget5(),
              ),
              Positioned(
                left: 283.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 33.0,
                child: GeneratedLogoutWidget5(),
              )
            ]),
      ),
    ));
  }
}
