import 'package:flutter/material.dart';
import '../../main.dart';
// import 'package:flutterapp/diyeyapp/generatedandroidsmall1widget/generated/GeneratedHomeWidget5.dart';
// import 'package:flutterapp/diyeyapp/generatedandroidsmall1widget/generated/GeneratedLogoutWidget5.dart';
// import 'package:flutterapp/diyeyapp/generatedandroidsmall1widget/generated/GeneratedRectangle28Widget.dart';
// import 'package:flutterapp/diyeyapp/generatedandroidsmall1widget/generated/GeneratedRectangle16Widget3.dart';
// import 'package:flutterapp/diyeyapp/generatedandroidsmall1widget/generated/GeneratedRectangle29Widget.dart';
// import 'package:flutterapp/diyeyapp/generatedandroidsmall1widget/generated/GeneratedImage2Widget1.dart';
// import 'package:flutterapp/diyeyapp/generatedandroidsmall1widget/generated/GeneratedFavoritWidget.dart';
// import 'package:flutterapp/diyeyapp/generatedandroidsmall1widget/generated/GeneratedRectangle27Widget.dart';
import 'package:flutter/gestures.dart';
import 'package:flutterapp/diyeyapp/generatedhomewidget/GeneratedHomeWidget.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../generatedloginwidget/generated/EmailForm.dart';

/* Frame Android Small - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall1Widget extends StatelessWidget {
  final user = FirebaseAuth.instance.currentUser!;

  @override
  Widget build(BuildContext context) {
    return Material(
      child: SingleChildScrollView(
          child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 640.0,
          child: Stack(
              clipBehavior: Clip.none,
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 34.0,
                  top: 215.0,
                  right: null,
                  bottom: null,
                  width: 297.0,
                  height: 283.0,
                  child: Container(
                    width: 297.0,
                    height: 283.0,
                    child: ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Image.asset(
                        "assets/images/e8a2f2c65f62ce6e8fe19f550a8d96ecb63ef8e2.png",
                        color: null,
                        fit: BoxFit.cover,
                        width: 297.0,
                        height: 283.0,
                        colorBlendMode: BlendMode.dstATop,
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 56.0,
                  top: 57.0,
                  right: null,
                  bottom: null,
                  width: 252.0,
                  height: 65.0,
                  child: Text(
                    '''Favorit''',
                    overflow: TextOverflow.visible,
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      height: 1.171875,
                      fontSize: 30.0,
                      fontFamily: 'Irish Grover',
                      fontWeight: FontWeight.w400,
                      color: Color.fromARGB(255, 0, 0, 0),

                      /* letterSpacing: 0.0, */
                    ),
                  ),
                ),
                Positioned(
                  left: 26.0,
                  top: 119.0,
                  right: null,
                  bottom: null,
                  width: 194.0,
                  height: 131.0,
                  child: Container(
                    width: 194.0,
                    height: 131.0,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(15.0),
                      border: Border.all(
                        width: 1.0,
                        color: Color.fromARGB(255, 0, 0, 0),
                      ),
                    ),
                    child: ClipRRect(
                      borderRadius: BorderRadius.circular(15.0),
                      child: Image.asset(
                        "assets/images/6164d3ccf366369173ff51910bcef72043ae1af5.png",
                        color: null,
                        fit: BoxFit.cover,
                        width: 194.0,
                        height: 131.0,
                        colorBlendMode: BlendMode.dstATop,
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 26.0,
                  top: 320.0,
                  right: null,
                  bottom: null,
                  width: 194.0,
                  height: 131.0,
                  child: Container(
                    width: 194.0,
                    height: 131.0,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(15.0),
                      border: Border.all(
                        width: 1.0,
                        color: Color.fromARGB(255, 0, 0, 0),
                      ),
                    ),
                    child: ClipRRect(
                      borderRadius: BorderRadius.circular(15.0),
                      child: Image.asset(
                        "assets/images/cbb7e3d5ab7cb5093435f211bcecba59b078ac73.png",
                        color: null,
                        fit: BoxFit.cover,
                        width: 194.0,
                        height: 131.0,
                        colorBlendMode: BlendMode.dstATop,
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 183.0,
                  top: 215.0,
                  right: null,
                  bottom: null,
                  width: 70.0,
                  height: 70.0,
                  child: Container(
                    width: 70.0,
                    height: 70.0,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(180.0),
                    ),
                    child: ClipRRect(
                      borderRadius: BorderRadius.circular(180.0),
                      child: Image.asset(
                        "assets/images/e31fed0fed011fa2146e60aeff6efa2f04a59d14.png",
                        color: null,
                        fit: BoxFit.cover,
                        width: 70.0,
                        height: 70.0,
                        colorBlendMode: BlendMode.dstATop,
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 180.0,
                  top: 416.0,
                  right: null,
                  bottom: null,
                  width: 70.0,
                  height: 70.0,
                  child: Container(
                    width: 70.0,
                    height: 70.0,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(180.0),
                    ),
                    child: ClipRRect(
                      borderRadius: BorderRadius.circular(180.0),
                      child: Image.asset(
                        "assets/images/e31fed0fed011fa2146e60aeff6efa2f04a59d14.png",
                        color: null,
                        fit: BoxFit.cover,
                        width: 70.0,
                        height: 70.0,
                        colorBlendMode: BlendMode.dstATop,
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 215.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 70.0,
                  height: 40.0,
                  child: Container(
                      margin: EdgeInsets.only(top: 20),
                      child: RichText(
                        text: TextSpan(
                            style: TextStyle(color: Colors.white, fontSize: 20),
                            children: [
                              TextSpan(
                                  recognizer: TapGestureRecognizer()
                                    ..onTap = () => Navigator.push(
                                        context,
                                        MaterialPageRoute(
                                            builder: (context) => MainPage())),
                                  text: 'Home |',
                                  style: TextStyle(
                                    decoration: TextDecoration.underline,
                                    color: Colors.black,
                                  ))
                            ]),
                      )),
                ),
                // Positioned(
                //   left: 283.0,
                //   top: 0.0,
                //   right: null,
                //   bottom: null,
                //   width: 86.0,
                //   height: 33.0,
                //   child: SizedBox(
                //     height: 30,
                //     width: 150,
                //     child: ElevatedButton(
                //       style: ElevatedButton.styleFrom(
                //         primary: Color.fromARGB(255, 255, 255, 255),
                //         shape: new RoundedRectangleBorder(
                //           borderRadius: new BorderRadius.circular(30.0),
                //         ),
                //       ),
                //       onPressed: () => Navigator.push(context,
                //           MaterialPageRoute(builder: (context) => MainPage())),
                //       child: const Text(
                //         '''Logout''',
                //         style: TextStyle(
                //           fontFamily: 'Inter',
                //           color: Color.fromARGB(255, 0, 0, 0),
                //         ),
                //       ),
                //     ),
                //   ),
                // )
              ]),
        ),
      )),
    );
  }
}
