// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALCtfFc3qrEHHkMaqq73S9UZ5Z9LybbQ4',
    appId: '1:131121666838:web:b78524e61c4ee468e4ce37',
    messagingSenderId: '131121666838',
    projectId: 'flutter-diy',
    authDomain: 'flutter-diy.firebaseapp.com',
    databaseURL: 'https://flutter-diy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-diy.appspot.com',
    measurementId: 'G-GW4SSSK6Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR0_8UaFWyCB7VQ1hPIVog4nui3FwJcF0',
    appId: '1:131121666838:android:2e6c6b558069a726e4ce37',
    messagingSenderId: '131121666838',
    projectId: 'flutter-diy',
    databaseURL: 'https://flutter-diy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-diy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCooirhIUmeqtdggBiBOFLahkN_wDufjA8',
    appId: '1:131121666838:ios:6876754bc2a35937e4ce37',
    messagingSenderId: '131121666838',
    projectId: 'flutter-diy',
    databaseURL: 'https://flutter-diy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-diy.appspot.com',
    iosClientId: '131121666838-kv6aqf7gvjimpon93qcbq2dl3od05i12.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterapp',
  );
}
