import 'package:flutter/material.dart';
import 'package:flutterapp/diyeyapp/generatedregisterwidget1/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/diyeyapp/generatedregisterwidget1/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/diyeyapp/generatedregisterwidget1/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/diyeyapp/generatedregisterwidget1/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/diyeyapp/generatedregisterwidget1/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/diyeyapp/generatedregisterwidget1/generated/GeneratedNameWidget.dart';
import 'package:flutterapp/diyeyapp/generatedregisterwidget1/generated/GeneratedPasswordWidget1.dart';
import 'package:flutterapp/diyeyapp/generatedregisterwidget1/generated/GeneratedRegisterWidget2.dart';
import 'package:flutterapp/diyeyapp/generatedregisterwidget1/generated/GeneratedEmailWidget.dart';
import 'package:flutterapp/diyeyapp/generatedregisterwidget1/generated/GeneratedBacktoLoginWidget.dart';
import 'package:flutterapp/diyeyapp/generatedregisterwidget1/generated/GeneratedRegistrasiWidget.dart';

/* Frame register
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegisterWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 231, 252),
                ),
              ),
              Positioned(
                left: 108.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 154.0,
                height: 45.0,
                child: GeneratedRegistrasiWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 45.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 261.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 45.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 45.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 122.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 40.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 56.0,
                top: 209.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 24.0,
                child: GeneratedNameWidget(),
              ),
              Positioned(
                left: 56.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 30.0,
                child: GeneratedEmailWidget(),
              ),
              Positioned(
                left: 56.0,
                top: 331.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 29.0,
                child: GeneratedPasswordWidget1(),
              ),
              Positioned(
                left: 142.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 37.0,
                child: GeneratedRegisterWidget2(),
              ),
              Positioned(
                left: 129.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 20.0,
                child: GeneratedBacktoLoginWidget(),
              ),
              Positioned(
                left: 127.0,
                top: 496.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 1.0,
                child: GeneratedLine2Widget(),
              )
            ]),
      ),
    ));
  }
}
