import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
// import 'package:flutterapp/diyeyapp/generatedtambahtutorialwidget1/generated/GeneratedTutorialWidget9.dart';
// import 'package:flutterapp/diyeyapp/generatedtambahtutorialwidget1/generated/GeneratedTambahWidget.dart';
// import 'package:flutterapp/diyeyapp/generatedtambahtutorialwidget1/generated/GeneratedTambahTutorialWidget.dart';
// import 'package:flutterapp/diyeyapp/generatedtambahtutorialwidget1/generated/GeneratedBahanWidget3.dart';
import 'package:flutterapp/diyeyapp/generatedhomewidget/GeneratedHomeWidget.dart';
import '../../main.dart';

/* Frame tambah tutorial
    Autogenerated by FlutLab FTF Generator
  */
class TambahTutorPage extends StatefulWidget {
  @override
  State<TambahTutorPage> createState() => _TambahTutorPageState();
}

class _TambahTutorPageState extends State<TambahTutorPage> {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: SingleChildScrollView(
          child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 640.0,
          child: Stack(
              clipBehavior: Clip.none,
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 231, 252),
                  ),
                ),
                Positioned(
                  left: 34.0,
                  top: 114.0,
                  right: null,
                  bottom: null,
                  width: 291.0,
                  height: 70.0,
                  child: Form(
                    child: Center(
                      child: Column(
                        children: [
                          Column(children: [
                            Container(
                              margin: EdgeInsets.only(top: 20),
                              padding: EdgeInsets.fromLTRB(20, 0, 0, 0),
                              decoration: BoxDecoration(
                                  color: Color.fromARGB(255, 254, 245, 255),
                                  borderRadius: BorderRadius.circular(14),
                                  border: Border.all(color: Colors.black)),
                              child: TextFormField(
                                textInputAction: TextInputAction.next,
                                decoration: InputDecoration(
                                  hintText: 'Gambar',
                                  hintStyle: TextStyle(
                                      fontSize: 16,
                                      fontWeight: FontWeight.w600,
                                      color: Color.fromARGB(255, 0, 0, 0)),
                                ),
                              ),
                            ),
                          ]),
                        ],
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 34.0,
                  top: 274.0,
                  right: null,
                  bottom: null,
                  width: 291.0,
                  height: 70.0,
                  child: Form(
                    child: Center(
                      child: Column(
                        children: [
                          Column(children: [
                            Container(
                              margin: EdgeInsets.only(top: 20),
                              padding: EdgeInsets.fromLTRB(20, 0, 0, 0),
                              decoration: BoxDecoration(
                                  color: Color.fromARGB(255, 239, 164, 246),
                                  borderRadius: BorderRadius.circular(14),
                                  border: Border.all(color: Colors.black)),
                              child: TextFormField(
                                textInputAction: TextInputAction.next,
                                decoration: InputDecoration(
                                  hintText: 'Judul',
                                  hintStyle: TextStyle(
                                      fontSize: 16,
                                      fontWeight: FontWeight.w600,
                                      color: Color.fromARGB(255, 0, 0, 0)),
                                ),
                              ),
                            ),
                          ]),
                        ],
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 34.0,
                  top: 354.0,
                  right: null,
                  bottom: null,
                  width: 291.0,
                  height: 70.0,
                  child: Form(
                    child: Center(
                      child: Column(
                        children: [
                          Column(children: [
                            Container(
                              margin: EdgeInsets.only(top: 20),
                              padding: EdgeInsets.fromLTRB(20, 0, 0, 0),
                              decoration: BoxDecoration(
                                  color: Color.fromARGB(255, 167, 146, 250),
                                  borderRadius: BorderRadius.circular(14),
                                  border: Border.all(color: Colors.black)),
                              child: TextFormField(
                                textInputAction: TextInputAction.next,
                                decoration: InputDecoration(
                                  hintText: 'Tutorial',
                                  hintStyle: TextStyle(
                                      fontSize: 16,
                                      fontWeight: FontWeight.w600,
                                      color: Color.fromARGB(255, 0, 0, 0)),
                                ),
                              ),
                            ),
                          ]),
                        ],
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 34.0,
                  top: 194.0,
                  right: null,
                  bottom: null,
                  width: 291.0,
                  height: 70.0,
                  child: Form(
                    child: Center(
                      child: Column(
                        children: [
                          Column(children: [
                            Container(
                              margin: EdgeInsets.only(top: 20),
                              padding: EdgeInsets.fromLTRB(20, 0, 0, 0),
                              decoration: BoxDecoration(
                                  color: Color.fromARGB(255, 241, 191, 245),
                                  borderRadius: BorderRadius.circular(14),
                                  border: Border.all(color: Colors.black)),
                              child: TextFormField(
                                textInputAction: TextInputAction.next,
                                decoration: InputDecoration(
                                  hintText: 'Bahan',
                                  hintStyle: TextStyle(
                                      fontSize: 16,
                                      fontWeight: FontWeight.w600,
                                      color: Color.fromARGB(255, 0, 0, 0)),
                                ),
                              ),
                            ),
                          ]),
                        ],
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 107.0,
                  top: 434.0,
                  right: null,
                  bottom: null,
                  width: 146.0,
                  height: 52.0,
                  child: Container(
                      margin: EdgeInsets.only(top: 20),
                      child: RichText(
                        text: TextSpan(
                            style: TextStyle(color: Colors.white, fontSize: 20),
                            children: [
                              TextSpan(
                                  recognizer: TapGestureRecognizer()
                                    ..onTap = () => Navigator.push(
                                        context,
                                        MaterialPageRoute(
                                            builder: (context) => MainPage())),
                                  text: 'Home |',
                                  style: TextStyle(
                                    decoration: TextDecoration.underline,
                                    color: Colors.black,
                                  ))
                            ]),
                      )),
                ),
                // Positioned(
                //   left: 56.0,
                //   top: 54.0,
                //   right: null,
                //   bottom: null,
                //   width: 249.0,
                //   height: 62.0,
                //   child: GeneratedTambahTutorialWidget(),
                // ),
                // Positioned(
                //   left: 56.0,
                //   top: 125.0,
                //   right: null,
                //   bottom: null,
                //   width: 131.0,
                //   height: 39.0,
                //   child: GeneratedGambarWidget(),
                // ),
                // Positioned(
                //   left: 56.0,
                //   top: 207.0,
                //   right: null,
                //   bottom: null,
                //   width: 112.0,
                //   height: 37.0,
                //   child: GeneratedJudulWidget(),
                // ),
                // Positioned(
                //   left: 53.0,
                //   top: 285.0,
                //   right: null,
                //   bottom: null,
                //   width: 112.0,
                //   height: 37.0,
                //   child: GeneratedBahanWidget3(),
                // ),
                // Positioned(
                //   left: 53.0,
                //   top: 368.0,
                //   right: null,
                //   bottom: null,
                //   width: 112.0,
                //   height: 37.0,
                //   child: GeneratedTutorialWidget9(),
                // ),
                // Positioned(
                //   left: 130.0,
                //   top: 445.0,
                //   right: null,
                //   bottom: null,
                //   width: 103.0,
                //   height: 35.0,
                //   child: GeneratedTambahWidget(),
                // ),
                // Positioned(
                //   left: 218.0,
                //   top: 0.0,
                //   right: null,
                //   bottom: null,
                //   width: 83.0,
                //   height: 30.0,
                //   child: GeneratedHomeWidget4(),
                // ),
                // Positioned(
                //   left: 289.0,
                //   top: 0.0,
                //   right: null,
                //   bottom: null,
                //   width: 76.0,
                //   height: 33.0,
                //   child: GeneratedLogoutWidget4(),
                // )
              ]),
        ),
      )),
    );
  }
}
