import 'package:flutter/material.dart';
import 'package:flutterapp/diyeyapp/generatedtambahtutorialwidget1/generated/GeneratedTutorialWidget9.dart';
import 'package:flutterapp/diyeyapp/generatedtambahtutorialwidget1/generated/GeneratedRectangle25Widget.dart';
import 'package:flutterapp/diyeyapp/generatedtambahtutorialwidget1/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/diyeyapp/generatedtambahtutorialwidget1/generated/GeneratedTambahWidget.dart';
import 'package:flutterapp/diyeyapp/generatedtambahtutorialwidget1/generated/GeneratedJudulWidget.dart';
import 'package:flutterapp/diyeyapp/generatedtambahtutorialwidget1/generated/GeneratedRectangle26Widget.dart';
import 'package:flutterapp/diyeyapp/generatedtambahtutorialwidget1/generated/GeneratedTambahTutorialWidget.dart';
import 'package:flutterapp/diyeyapp/generatedtambahtutorialwidget1/generated/GeneratedHomeWidget4.dart';
import 'package:flutterapp/diyeyapp/generatedtambahtutorialwidget1/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/diyeyapp/generatedtambahtutorialwidget1/generated/GeneratedRectangle23Widget.dart';
import 'package:flutterapp/diyeyapp/generatedtambahtutorialwidget1/generated/GeneratedBahanWidget3.dart';
import 'package:flutterapp/diyeyapp/generatedtambahtutorialwidget1/generated/GeneratedGambarWidget.dart';
import 'package:flutterapp/diyeyapp/generatedtambahtutorialwidget1/generated/GeneratedLogoutWidget4.dart';

/* Frame tambah tutorial
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTambahtutorialWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 231, 252),
                ),
              ),
              Positioned(
                left: 34.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 291.0,
                height: 59.0,
                child: GeneratedRectangle19Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 274.0,
                right: null,
                bottom: null,
                width: 291.0,
                height: 59.0,
                child: GeneratedRectangle25Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 291.0,
                height: 59.0,
                child: GeneratedRectangle26Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 194.0,
                right: null,
                bottom: null,
                width: 291.0,
                height: 59.0,
                child: GeneratedRectangle24Widget(),
              ),
              Positioned(
                left: 107.0,
                top: 434.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 52.0,
                child: GeneratedRectangle23Widget(),
              ),
              Positioned(
                left: 56.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 62.0,
                child: GeneratedTambahTutorialWidget(),
              ),
              Positioned(
                left: 56.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 131.0,
                height: 39.0,
                child: GeneratedGambarWidget(),
              ),
              Positioned(
                left: 56.0,
                top: 207.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 37.0,
                child: GeneratedJudulWidget(),
              ),
              Positioned(
                left: 53.0,
                top: 285.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 37.0,
                child: GeneratedBahanWidget3(),
              ),
              Positioned(
                left: 53.0,
                top: 368.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 37.0,
                child: GeneratedTutorialWidget9(),
              ),
              Positioned(
                left: 130.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 35.0,
                child: GeneratedTambahWidget(),
              ),
              Positioned(
                left: 218.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 30.0,
                child: GeneratedHomeWidget4(),
              ),
              Positioned(
                left: 289.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 33.0,
                child: GeneratedLogoutWidget4(),
              )
            ]),
      ),
    ));
  }
}
