import 'package:flutter/material.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget5/generated/Generatedpotongbotoldanbalutdengankertasbalutbibirvasdenganwarna.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget5/generated/GeneratedBotolplastikkertassampulwarnahijaumerahhijaumudasisaker.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget5/generated/GeneratedTempatTisuDariStikEsKrimWidget1.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget5/generated/GeneratedHomeWidget2.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget5/generated/GeneratedRectangle17Widget1.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget5/generated/GeneratedEllipse1Widget1.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget5/generated/GeneratedTutorialWidget6.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget5/generated/GeneratedRectangle16Widget1.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget5/generated/GeneratedImage2Widget.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget5/generated/GeneratedLogoutWidget2.dart';
import 'package:flutterapp/diyeyapp/generatedtutorialwidget5/generated/GeneratedBahanWidget1.dart';

/* Frame tutorial
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTutorialWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 36.0,
                top: 184.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 166.0,
                child: GeneratedRectangle16Widget1(),
              ),
              Positioned(
                left: 35.0,
                top: 396.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 227.0,
                child: GeneratedRectangle17Widget1(),
              ),
              Positioned(
                left: 124.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 111.0,
                child: GeneratedEllipse1Widget1(),
              ),
              Positioned(
                left: 44.0,
                top: 229.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 105.0,
                child:
                    GeneratedBotolplastikkertassampulwarnahijaumerahhijaumudasisaker(),
              ),
              Positioned(
                left: 50.0,
                top: 195.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 23.0,
                child: GeneratedBahanWidget1(),
              ),
              Positioned(
                left: 22.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 47.0,
                child: GeneratedTempatTisuDariStikEsKrimWidget1(),
              ),
              Positioned(
                left: 38.0,
                top: 401.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 219.0,
                child:
                    Generatedpotongbotoldanbalutdengankertasbalutbibirvasdenganwarna(),
              ),
              Positioned(
                left: 47.0,
                top: 370.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 28.0,
                child: GeneratedTutorialWidget6(),
              ),
              Positioned(
                left: 244.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 70.04717254638672,
                child: GeneratedImage2Widget(),
              ),
              Positioned(
                left: 211.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 30.0,
                child: GeneratedHomeWidget2(),
              ),
              Positioned(
                left: 286.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 33.0,
                child: GeneratedLogoutWidget2(),
              )
            ]),
      ),
    ));
  }
}
